In [11]:
import pickle
import pandas as pd

In [34]:
data_file_path = 'cif_raw_data.pickle'
with open(data_file_path, 'rb') as f:
    data_dictionary = pickle.load(f)

ca_file_path = './uky_ca.csv'
ca = pd.read_csv(ca_file_path, dtype={'FIPS':str})
ca['County'] = ca.County + ' County'

from utils import stateDf

In [84]:
def select_area_for_catchment_area(df, query_level, ca = ca):
    if hasattr(df, 'County'):
        if df.County[0][-6:].lower() != 'county':
            df['County'] = df.County + ' County'

    if query_level == 'county':
        return df.loc[df.FIPS.isin(ca.FIPS), :].reset_index(drop = True)
    elif query_level in ['county subdivision','tract','block']:
        if hasattr(df, 'FIPS5'):
            df = df.loc[df.FIPS5.isin(ca.FIPS), :].reset_index(drop = True)
            df.drop('FIPS5', axis = 1, inplace = True)
        else:
            df = df.loc[df.FIPS.apply(lambda x: x[:5]).isin(ca.FIPS), :].reset_index(drop = True)
        return df

#### places data

In [93]:
def gen_long_risk_and_screening(data_dictionary = data_dictionary):
    df_county = data_dictionary['county']['risk_and_screening'].copy()
    df_tract  = data_dictionary['tract']['risk_and_screening'].copy()
    
    df_county = select_area_for_catchment_area(df_county, 'county')
    df_tract = select_area_for_catchment_area(df_county, 'tract')
    
    df_county_l = pd.melt(df_county, id_vars=['FIPS', 'County', 'State'], 
                         var_name='measure', value_name='value')

    df_tract_l = pd.melt(df_tract, id_vars=['FIPS', 'County', 'State'], 
                         var_name='measure', value_name='value')

    return df_county_l, df_tract_l

In [94]:
cdc_county_l, cdc_tract_l = gen_long_risk_and_screening()

#### gen_cancer_data

In [203]:
data_dictionary = {'cancer': dd}
cancer_inc_l = data_dictionary['cancer']['incidence'].copy()
cancer_inc_l = select_area_for_catchment_area(cancer_inc_l, 'county')
cancer_inc_l = cancer_inc_l[['FIPS', 'County', 'State', 'Type', 'Site', 'AAR', 'AAC']]
cancer_inc = pd.pivot(cancer_inc_l, index=['FIPS', 'County', 'State', 'Type'], columns='Site', values='AAR')
cancer_mor_l = data_dictionary['cancer']['mortality'].copy()
cancer_mor_l = select_area_for_catchment_area(cancer_mor_l, 'county')
cancer_mor_l = cancer_mor_l[['FIPS', 'County', 'State', 'Type', 'Site', 'AAR', 'AAC']]
cancer_mor = pd.pivot(cancer_mor_l, index=['FIPS', 'County', 'State', 'Type'], columns='Site', values='AAR')

KeyError: "['State'] not in index"

In [ ]:
    def gen_cancer_data():
        print('Collecting cancer incidence and mortality data...')
        inc_data = pd.DataFrame()
        mor_data = pd.DataFrame()
        
        for s in caStateFIPS:
            cnr = scp_cancer_data(state = s)
            inc_data = pd.concat([inc_data, cnr.incidence], ignore_index=True)
            mor_data = pd.concat([mor_data, cnr.mortality], ignore_index=True)
            del cnr
        
        inc_data = inc_data.merge(stateDf, on='FIPS2', how='left')
        caInc = inc_data[['FIPS', 'County', 'State', 'Type', 'Site', 'AAR', 'AAC']]
        caInc = caInc[caInc['FIPS'].isin(caFIPS)]
        
        mor_data = mor_data.merge(stateDf, on='FIPS2', how='left')
        caMor = mor_data[['FIPS', 'County', 'State', 'Type', 'Site', 'AAR', 'AAC']]
        caMor = caMor[caMor['FIPS'].isin(caFIPS)]
        
        return({'cancer_incidence': caInc, 'cancer_mortality': caMor})

#### econ_data

In [280]:
data_dictionary['tract'].keys()

dict_keys(['insurance', 'vacancy', 'poverty', 'transportation', 'employment', 'gini_index', 'rent_to_income', 'houses_before_1960', 'public_assistance', 'education', 'income', 'demographic_age', 'demographic_race', 'risk_and_screening', 'food_desert'])

In [281]:
econ_topics = ['insurance','gini_index','income','employment','poverty','bls_unemployment']

In [293]:
colnames = {'Labor Force Participation Rate': f'Annual Labor Force Participation Rate (2015-2019)',
            'Unemployment Rate' : f'Annual Unemployment Rate (2015-2019)',
            'health_insurance_coverage_rate': 'Insurance Coverage',
            'Gini Index': 'Gini Coefficient',
            'median_income_all': 'Household Income',
            'medicaid' : 'Medicaid Enrollment',
            'below_poverty' : 'Below Poverty'
            }

In [305]:
econ_county_datasets = [select_area_for_catchment_area(data_dictionary['county'][topic], query_level = 'county') for topic in econ_topics]

In [306]:
def merge_all(*args, query_level = 'county'):
    if query_level == 'county':
        geo_col = ['FIPS','County','State']
    elif query_level == 'tract':
        geo_col = ['FIPS','Tract','County','State']
    datasets_to_merge = []
    datasets_not_to_merge = []
    columns_to_be_used_later = []
    for df in args:
        if all([hasattr(df, col) for col in geo_col]):
            datasets_to_merge.append(df)
        else:
            datasets_not_to_merge.append(df)
            columns_to_be_used_later.append(pd.Series(geo_col)[[hasattr(df, col) for col in geo_col]].tolist())
    for i, df in enumerate(datasets_to_merge):
        if i == 0:
            for col in geo_col:
                assert hasattr(df, col)
            output = df.copy()
        else:
            output = output.merge(df, how = 'left', on = geo_col)
    if len(datasets_not_to_merge):
        for df, merge_on_col in zip(datasets_not_to_merge, columns_to_be_used_later):
            output = output.merge(df, how = 'left', on = merge_on_col)
    return output

In [307]:
df = merge_all(*econ_county_datasets, query_level = 'county')

In [308]:
df = df.rename(columns = colnames)

In [309]:
df = df.drop(columns=['below_poverty_x.5', 'below_poverty_x2'], axis= 1)

In [310]:
df['Uninsured'] = 1-df['Insurance Coverage']

In [311]:
df

,FIPS,County,State,Insurance Coverage,Medicaid Enrollment,Gini Coefficient,Household Income,Annual Labor Force Participation Rate (2015-2019),Annual Unemployment Rate (2015-2019),Below Poverty,Monthly Unemployment Rate (Nov-22),Uninsured
0,21079,Garrard County,Kentucky,0.896667,0.225810,0.4339,52631.0,0.571408,0.065322,0.115898,0.038,0.103333
1,21037,Campbell County,Kentucky,0.930008,0.139810,0.4625,63050.0,0.647659,0.039937,0.093843,0.032,0.069992
2,21063,Elliott County,Kentucky,0.890973,0.446156,0.4535,32306.0,0.275785,0.015535,0.263896,0.079,0.109027
3,21123,Larue County,Kentucky,0.912593,0.268258,0.4455,47643.0,0.585319,0.044148,0.109995,0.041,0.087407
4,21167,Mercer County,Kentucky,0.903325,0.185784,0.4233,55093.0,0.604681,0.077121,0.097264,0.037,0.096675
...,...,...,...,...,...,...,...,...,...,...,...,...
115,21049,Clark County,Kentucky,0.924715,0.240744,0.4544,54953.0,0.602127,0.055710,0.110832,0.034,0.075285
116,21219,Todd County,Kentucky,0.816357,0.237257,0.4911,44005.0,0.540849,0.072767,0.149044,0.034,0.183643
117,21041,Carroll County,Kentucky,0.907516,0.310076,0.4884,43524.0,0.591665,0.079116,0.220280,0.032,0.092484
118,21053,Clinton County,Kentucky,0.887516,0.386570,0.5177,32184.0,0.473376,0.062178,0.175881,0.044,0.112484
119,21077,Gallatin County,Kentucky,0.927744,0.207967,0.3889,52167.0,0.597516,0.055501,0.121927,0.036,0.072256

In [312]:
econ_county_l = pd.melt(df, id_vars = ['FIPS', 'County', 'State'], 
                        var_name = 'measure', value_name = 'value')

In [313]:
econ_county_l

       FIPS           County     State             measure     value
0     21079   Garrard County  Kentucky  Insurance Coverage  0.896667
1     21037  Campbell County  Kentucky  Insurance Coverage  0.930008
2     21063   Elliott County  Kentucky  Insurance Coverage  0.890973
3     21123     Larue County  Kentucky  Insurance Coverage  0.912593
4     21167    Mercer County  Kentucky  Insurance Coverage  0.903325
...     ...              ...       ...                 ...       ...
1075  21049     Clark County  Kentucky           Uninsured  0.075285
1076  21219      Todd County  Kentucky           Uninsured  0.183643
1077  21041   Carroll County  Kentucky           Uninsured  0.092484
1078  21053   Clinton County  Kentucky           Uninsured  0.112484
1079  21077  Gallatin County  Kentucky           Uninsured  0.072256

[1080 rows x 5 columns]

In [302]:
# the same process goes for tract level

#### housing and transportation

In [315]:
ht_topic = ['vacancy','transportation']

In [316]:
colnames = {'vacancy_rate': 'Vacancy Rate', 'no_vehicle': 'No Vehicle',
                                         'rent_over_40':'Rent Burden (40% Income)'}

In [317]:
cols_to_drop = ['two_or_more_vehicle','three_or_more_vehicle']

In [320]:
ht_county_datasets = [select_area_for_catchment_area(
    data_dictionary['county'][topic], query_level = 'county') for topic in ht_topic]

In [321]:
df = merge_all(*ht_county_datasets, query_level = 'county')

In [323]:
df = df.drop(cols_to_drop, axis = 1)

In [325]:
df = df.rename(columns = colnames)

In [327]:
df = df.sort_values('FIPS').reset_index(drop = True)

In [328]:
df

      FIPS           County     State  Vacancy Rate  No Vehicle
0    21001     Adair County  Kentucky      0.189569    0.017157
1    21003     Allen County  Kentucky      0.197954    0.044648
2    21005  Anderson County  Kentucky      0.076089    0.007975
3    21007   Ballard County  Kentucky      0.217513    0.019596
4    21009    Barren County  Kentucky      0.139772    0.021463
..     ...              ...       ...           ...         ...
115  21231     Wayne County  Kentucky      0.248859    0.018417
116  21233   Webster County  Kentucky      0.168960    0.012682
117  21235   Whitley County  Kentucky      0.183277    0.021082
118  21237     Wolfe County  Kentucky      0.222222    0.071186
119  21239  Woodford County  Kentucky      0.070300    0.020943

[120 rows x 5 columns]

In [329]:
# The same goes for tract

#### Sociodemographic

In [330]:
data_dictionary['county'].keys()

dict_keys(['insurance', 'vacancy', 'poverty', 'transportation', 'employment', 'gini_index', 'rent_to_income', 'houses_before_1960', 'public_assistance', 'education', 'income', 'demographic_age', 'demographic_race', 'risk_and_screening', 'bls_unemployment', 'food_desert', 'water_violation'])

In [350]:
socio_topic = ['demographic_age','demographic_race','education','urban_rural']

In [358]:
socio_county_datasets = [select_area_for_catchment_area(
    data_dictionary['county'][topic], query_level = 'county') for topic in socio_topic \
                         if topic in data_dictionary['county'].keys()]

In [352]:
df = merge_all(*socio_county_datasets, query_level = 'county')

In [355]:
df = df.sort_values('FIPS').reset_index(drop = True)

In [356]:
sd_county_l = pd.melt(df, id_vars = ['FIPS', 'County', 'State'], 
                        var_name = 'measure', value_name = 'value')

In [357]:
sd_county_l

       FIPS           County     State           measure       value
0     21001     Adair County  Kentucky          Under 18   3749.0000
1     21003     Allen County  Kentucky          Under 18   4982.0000
2     21005  Anderson County  Kentucky          Under 18   5348.0000
3     21007   Ballard County  Kentucky          Under 18   1765.0000
4     21009    Barren County  Kentucky          Under 18  10480.0000
...     ...              ...       ...               ...         ...
1555  21231     Wayne County  Kentucky  Urban_Percentage      0.3227
1556  21233   Webster County  Kentucky  Urban_Percentage      0.0000
1557  21235   Whitley County  Kentucky  Urban_Percentage      0.3484
1558  21237     Wolfe County  Kentucky  Urban_Percentage      0.0000
1559  21239  Woodford County  Kentucky  Urban_Percentage      0.6384

[1560 rows x 5 columns]

In [ ]:
# Same goes for tract level

#### env_data

In [370]:
env_topic = ['water_violation','food_desert']

In [380]:
env_data_county = data_dictionary['county']['vacancy'].merge(data_dictionary['county']['water_violation'], on = ['County','State']).sort_values('FIPS').reset_index(drop = True)

In [383]:
env_data_county.drop(['vacancy_rate'], axis = 1, inplace = True)
env_data_county.merge(data_dictionary['county']['food_desert'])

      FIPS           County     State  Counts  LILATracts_Vehicle
0    21001     Adair County  Kentucky     0.0            0.241592
1    21003     Allen County  Kentucky     2.0            0.000000
2    21005  Anderson County  Kentucky     2.0            0.000000
3    21007   Ballard County  Kentucky     0.0            0.296732
4    21009    Barren County  Kentucky     0.0            0.237367
..     ...              ...       ...     ...                 ...
115  21231     Wayne County  Kentucky     1.0            0.770992
116  21233   Webster County  Kentucky    14.0            0.320182
117  21235   Whitley County  Kentucky     6.0            0.431234
118  21237     Wolfe County  Kentucky     9.0            1.000000
119  21239  Woodford County  Kentucky     0.0            0.000000

[120 rows x 5 columns]

In [377]:
data_dictionary['tract']['vacancy'].merge(data_dictionary['tract']['food_desert']).drop(['vacancy_rate','OHU2010'],axis = 1)

,FIPS,Tract,County,State,LILATracts_Vehicle
0,22071001744,Census Tract 17.44,Orleans Parish,Louisiana,1
1,22071001746,Census Tract 17.46,Orleans Parish,Louisiana,1
2,22071001745,Census Tract 17.45,Orleans Parish,Louisiana,1
3,22071001747,Census Tract 17.47,Orleans Parish,Louisiana,0
4,22071001748,Census Tract 17.48,Orleans Parish,Louisiana,0
...,...,...,...,...,...
2234,21095970200,Census Tract 9702,Harlan County,Kentucky,1
2235,21095970900,Census Tract 9709,Harlan County,Kentucky,1
2236,21095970100,Census Tract 9701,Harlan County,Kentucky,0
2237,21095970700,Census Tract 9707,Harlan County,Kentucky,1
2238,21095970800,Census Tract 9708,Harlan County,Kentucky,0

In [ ]:
def comp_data():
#     env = gen_env_data()
#     env_county, env_tract, broadband_data = env['environment_county'], env['environment_tract'], env['broadband_speeds']
    env_county_l = pd.melt(env_county, id_vars = ['FIPS', 'County', 'State'], 
                            var_name = 'measure', value_name = 'value')
    env_tract_l = pd.melt(env_tract, id_vars = ['FIPS', 'County', 'State', 'Census_Tract_2019'], 
                            var_name = 'measure', value_name = 'value')
#     point_df = gen_location_data()

In [20]:
hasattr(df, 'FIPS')

True